# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'deneme.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 366)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 70, 47, 13))
        self.label.setObjectName("label")
        self.txt_say2 = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_say2.setGeometry(QtCore.QRect(120, 110, 113, 20))
        self.txt_say2.setObjectName("txt_say2")
        self.txt_say1 = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_say1.setGeometry(QtCore.QRect(120, 70, 113, 20))
        self.txt_say1.setObjectName("txt_say1")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 110, 47, 13))
        self.label_2.setObjectName("label_2")
        self.btn_toplama = QtWidgets.QPushButton(self.centralwidget)
        self.btn_toplama.setGeometry(QtCore.QRect(60, 180, 75, 23))
        self.btn_toplama.setObjectName("btn_toplama")
        self.btn_cikarma = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cikarma.setGeometry(QtCore.QRect(160, 180, 75, 23))
        self.btn_cikarma.setObjectName("btn_cikarma")
        self.btn_carpma = QtWidgets.QPushButton(self.centralwidget)
        self.btn_carpma.setGeometry(QtCore.QRect(260, 180, 75, 23))
        self.btn_carpma.setObjectName("btn_carpma")
        self.btn_bolme = QtWidgets.QPushButton(self.centralwidget)
        self.btn_bolme.setGeometry(QtCore.QRect(370, 180, 75, 23))
        self.btn_bolme.setObjectName("btn_bolme")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 250, 121, 21))
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "SAYI 1:"))
        self.label_2.setText(_translate("MainWindow", "SAYI 2:"))
        self.btn_toplama.setText(_translate("MainWindow", "TOPLAMA"))
        self.btn_cikarma.setText(_translate("MainWindow", "ÇIKARMA"))
        self.btn_carpma.setText(_translate("MainWindow", "ÇARPMA"))
        self.btn_bolme.setText(_translate("MainWindow", "BÖLME"))
        self.label_3.setText(_translate("MainWindow", "Sonuç:"))
